### ISSUE TITLE
libffmpeg.so not available

### ISSUE THREAD

**Issue by paulfantom** [AgostonSzepessy/mattermost-desktop-rpm#1]
I was trying to install mattermost-desktop on Fedora 26 but it fails with this error:
```
Error: 
 Problem: conflicting requests
  - nothing provides libffmpeg.so()(64bit) needed by mattermost-desktop-3.7.1-1.fc26.x86_64
```

I have rpmfusion free and nonfree enabled but this doesn't help.

**Comment by AgostonSzepessy** [comment]
I have excluded `libffmpeg.so` from the dependency resolution. Could you try installing it again please? Let me know if it works.

**Comment by paulfantom** [comment]
Now it works. Thanks :+1:
